### ISSUE TITLE
Add option to choose whether or not data are converted to numpy array before sending to encoders

### ISSUE THREAD

**Issue by dataright-ai** [maxsch3/keras-batchflow#110]
Some encoders might require pandas Series object rather than a NumPy array. 
Some types of processing are more convenient in pandas than in numpy, e.g. pandas' universal fillna for all datatypes is much more convenient than functions in numpy.
Some of the datatypes are not supported in numpy, e.g. IntegerArray offering nullable int type

Currently, VarShaper hardcoded to convert pandas series objects representing variable values to numpy array before sending to an encoder.

**Comment by dataright-ai** [comment]
The functionality was implemented using adaptor classes and polymorphism. Two standard adaptors were added: numpy and pandas for numpy and pandas based encoders. 

BatchGenerator now has new parameter: encoder_adaptor, str ('numpy' or 'pandas') or instance of IEncoderAdaptor class

One can easily create a custom encoder_adaptor by defining a custom class from IEncoderAdaptor. Its instance if then needs to be provided in parameter encoder_adaptor

**Comment by maxsch3** [comment]
The new parameter encoder_adaptor was added to the BatchGenerator. By default, it is set for numpy endcoders.

It supports the following values:
- 'numpy' default, sets batch generator to send numpy arrays to encoders
- 'pandas' sets batch generator to send unconverted pandas Series to the encoders
- instance of a custom implementation of IEncoderAdaptor class for custom behaviour

The issue is closed
